apiVersion: v2
name: k8dev
description: Kubernetes Local Development Environment
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: cert-manager
    version: "v1.17.1"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
  - name: ingress-nginx
    version: "4.12.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled
  - name: loki-stack
    version: "2.9.11"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
  - name: grafana
    version: "6.60.6"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled