name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y make kubectl
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install -y helm

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d --version

      - name: Create k3d cluster
        run: |
          k3d cluster create test-cluster --wait
          kubectl cluster-info

      - name: Install k8dev
        run: make install

      - name: Check installation
        run: make check

      - name: Test infrastructure
        run: |
          k8dev install
          k8dev create test.local
          k8dev start test.local
          k8dev stop test.local
          k8dev uninstall

      - name: Cleanup
        if: always()
        run: |
          make uninstall
          k3d cluster delete test-cluster || true