name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y make kubectl helm

      - name: Install k3d
        run: |
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Create k3d cluster
        run: |
          k3d cluster create test-cluster

      - name: Install k8dev
        run: make install

      - name: Check installation
        run: make check

      - name: Test infrastructure
        run: |
          k8dev install
          k8dev create test.local
          k8dev start test.local
          k8dev stop test.local
          k8dev uninstall

      - name: Cleanup
        if: always()
        run: |
          make uninstall
          k3d cluster delete test-cluster